### ISSUE TITLE
Making interactions work

### ISSUE THREAD

**Issue by Yakito** [kennedyrose/webflow-on-next#1]
Hi! first of all, thanks for this! really interesting. 

I am interested in making interactions work, but now sure where to start. I see that there are no errors in the console and when I set a breakpoint in the JS file in charge of the interactions it gets fired, but then nothing happens.

Any suggestions/ideas at what should I be looking to make them work?
Thanks again!

**Comment by kennedyrose** [comment]
Sure! I started looking into this at one point. I'll pick it up if I ever have a need for interactions again, but right now I don't.

So the problem is with how Next.js loads JS and how Webflow needs it loaded. Since Next.js uses client-side routing when you're in the app, it doesn't load Webflow's JS every page transition. It only loads it on the first app load.

So basically:

- Webflow needs JS to run SSR-style every single page load
- Next.js runs JS client-style on history change

You can try to find a different way of asynchronously loading Webflow's JS every page view change with `useEffect` or something similar. But I'm not sure.

Let me know if you find a solution for this. Otherwise, I'll let you know if I jump back on this issue in the future.

**Comment by nsakibp** [comment]
@Yakito 
Did you try what @kennedyrose suggested ?

Just wanted to know if any workaround

**Comment by pehcastro** [comment]
Any news about the interactions? it would be great to be able to insert the webflow js into next.

**Comment by kennedyrose** [comment]
Hi guys! We've launched DesignSync.js which allows you to use interactions with your Next.js/Webflow site. You can check it out here: [https://designsync.app/](https://designsync.app/)
